version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: aimentor_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aimentor
    ports:
      - "5433:5432"